version: '2'
checks:
    argument-count:
        enabled: true
        config:
            threshold: 4
    complex-logic:
        enabled: true
        config:
            threshold: 4
    file-lines:
        enabled: true
        config:
            threshold: 250
    method-complexity:
        enabled: true
        config:
            threshold: 5
    method-count:
        enabled: true
        config:
            threshold: 20
    method-lines:
        enabled: true
        config:
            threshold: 25
    nested-control-flow:
        enabled: true
        config:
            threshold: 4
    return-statements:
        enabled: true
        config:
            threshold: 4
    similar-code:
        enabled: true
        config:
            threshold: null
    identical-code:
        enabled: true
        config:
            threshold: null
plugins:
    phpcodesniffer:
        enabled: true
        config:
            standard: "WordPress-Extra,WordPress-VIP"

exclude_patterns:
    - .github/
    - .vscode/
    - dist/
    - lib/
    - 'src/php/i18n.php'
    - 'src/php/fieldmaps.php'
    - '**/node_modules/'
    - '**/vendor/'
    - '**/__tests__/'
    - '**/__mocks__/'
    - '**/*.d.ts'
