printWidth = 80
singleQuote = true
tabWidth = 4
trailingComma = 'all'

[[overrides]]
  files = '*.js'
  [overrides.options]
    trailingComma = 'es5'

[[overrides]]
  files = '.?*.yml'
  [overrides.options]
    tabWidth = 2

[[overrides]]
  files = '*.{json,yml}'
  [overrides.options]
    tabWidth = 2

[[overrides]]
  files = '.babelrc'
  [overrides.options]
    tabWidth = 2
