language: nodejs
node_js:
    - "6"
before_script:
    - nvm install node
    - node --version
    - npm --version
    - nvm --version
    - npm install
script:
    - npm test
    - npm run lint
after_success:
    - bash <(curl -s https://codecov.io/bash)
branches:
    only:
        - master
        - /^greenkeeper-.*$/
cache:
    directories:
        - node_modules
