language: node_js
node_js:
    - "node"
branches:
    only:
        - master
        - /^greenkeeper-.*$/
cache:
    directories:
        - "node_modules"
after_success:
    - bash <(curl -s https://codecov.io/bash)
