version: '3.7'
services:
  wordpress:
    image: visiblevc/wordpress:0.23.0-php7.3
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      DB_PASS: root
      EXTRA_PHP: |
        define('SCRIPT_DEBUG', true);
      PLUGINS: >-
        classic-editor
        gutenberg
        query-monitor
      WP_DEBUG: 'true'
      WP_DEBUG_DISPLAY: 'true'
      WP_VERSION: nightly
    ports:
      - 8080:80
    volumes:
      - ./dist:/app/wp-content/plugins/academic-bloggers-toolkit
      - ./scripts/init:/docker-entrypoint-initwp.d

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - data:/var/lib/mysql
    ports:
      - 22222:80

volumes:
  data:
