version: '3.7'
services:
  wordpress:
    image: visiblevc/wordpress:0.22.0-php7.3
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    environment:
      DB_PASS: root
      WP_DEBUG: 'true'
      WP_DEBUG_DISPLAY: 'true'
      PLUGINS: >-
        classic-editor
        gutenberg
        query-monitor
      EXTRA_PHP: |
        define('SCRIPT_DEBUG', true);

    ports:
      - 8080:80
    volumes:
      - ./dist:/app/wp-content/plugins/academic-bloggers-toolkit
      - ./scripts/init-wp.sh:/docker-entrypoint-initwp.d/init-wp.sh
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
      - data:/var/lib/mysql
    ports:
      - 22222:80

volumes:
  data:
